### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by hainghia** [rkudryashov/graphql-rust-demo#3]
![image](https://user-images.githubusercontent.com/38345392/218369693-e0dc9e13-9b99-4807-8573-ef81fa5e618d.png)
Thank you for checking it out at auth_service:
- I logged in, and was returned the token. But when I use that code to authenticate create new account it returns error code:
```json
{
  "data": null,
  "errors": [
    {
      "message": "Forbidden",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createUser"
      ]
    }
  ]
}
````

- In case I don't enter the token or authenticate the token incorrectly, but I add a field "role":"ADMIN", the authentication is successful, I don't know if it's a bug or not (Illustration image)

**Comment by rkudryashov** [comment]
Currently, the authentication is performed in [apollo-router](https://github.com/rkudryashov/graphql-rust-demo/tree/master/apollo-router). All downstream services including `auth-service` don't require a token.

More info in the [article](https://romankudryashov.com/blog/2022/07/apollo-router/).

Obtaining a token can also be executed through `apollo-router`

**Comment by rkudryashov** [comment]
> Can you explain to me why when I put "role":"ADMIN" and header it passes the validation.

It is supposed to work in this way. The service just [checks ](https://github.com/rkudryashov/graphql-rust-demo/blob/master/auth-service/src/graphql.rs#L33) a role in the header against the value in the role guard. Some GraphQL operations in other services in this project don't even do that and execute requests without role header.

>I'm a bit worried if users know the PORT of "auth_service" they can access my system without token

They can if the port is accessible from the web. But that should not be the case when using such an architecture where Apollo Router receives all requests and routes them to downstream services.

**Comment by rkudryashov** [comment]
Thank you for finding the bug :) Please check whether the latest commit fixed it
