### ISSUE TITLE
The GetPlanet and GetPlanet api do not show satellites information.

### ISSUE THREAD

**Issue by hainghia** [rkudryashov/graphql-rust-demo#5]
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/38345392/230711442-9915dab4-da7b-4281-9d76-23deac32d6d1.png">
When I make a query from the above APIs, I can't get satellites information, please help me check it

**Comment by rkudryashov** [comment]
Accordingly to [Wikipedia](https://en.wikipedia.org/wiki/Venus)

> Venus has no natural satellites.

So a service's response is empty list.

You could try other id, for example, 3 (Earth) or 4 (Mars)

**Comment by rkudryashov** [comment]
I'm not planning to do it in the near future
